//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicPOS.Globalization.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс был автоматически создан классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resx_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicPOS.Globalization.Resources.Localization.Resx.ru-RU", typeof(Resx_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string global_error {
            get {
                return ResourceManager.GetString("global_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        public static string global_ok {
            get {
                return ResourceManager.GetString("global_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string global_cancel {
            get {
                return ResourceManager.GetString("global_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string global_save {
            get {
                return ResourceManager.GetString("global_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string global_edit {
            get {
                return ResourceManager.GetString("global_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string global_delete {
            get {
                return ResourceManager.GetString("global_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string global_add {
            get {
                return ResourceManager.GetString("global_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string global_close {
            get {
                return ResourceManager.GetString("global_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        public static string global_open {
            get {
                return ResourceManager.GetString("global_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string global_search {
            get {
                return ResourceManager.GetString("global_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string global_filter {
            get {
                return ResourceManager.GetString("global_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string global_refresh {
            get {
                return ResourceManager.GetString("global_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        public static string global_print {
            get {
                return ResourceManager.GetString("global_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        public static string global_export {
            get {
                return ResourceManager.GetString("global_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт.
        /// </summary>
        public static string global_import {
            get {
                return ResourceManager.GetString("global_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string global_language {
            get {
                return ResourceManager.GetString("global_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}
        ///
        ///Приложение не зарегистрировано!.
        /// </summary>
        public static string app_error_application_unlicenced_function_disabled {
            get {
                return ResourceManager.GetString("app_error_application_unlicenced_function_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратитесь в службу поддержки.
        /// </summary>
        public static string app_error_contact_support {
            get {
                return ResourceManager.GetString("app_error_contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка рендеринга темы: {0}
        ///
        ///Ошибка: {1}.
        /// </summary>
        public static string app_error_rendering_theme {
            get {
                return ResourceManager.GetString("app_error_rendering_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружено неподдерживаемое разрешение экрана: {0}x{1}
        ///
        ///Минимальное поддерживаемое разрешение: {2}x{3}.
        /// </summary>
        public static string app_error_unsupported_resolution_detected {
            get {
                return ResourceManager.GetString("app_error_unsupported_resolution_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует обязательный плагин типа SoftwareVendor или недействительный закрытый ключ для связи между библиотеками!
        ///
        ///Этот плагин необходим, без него некоторые функции будут отключены!
        ///
        ///Установите действительный плагин SoftwareVendor, который работает с зарегистрированной LogicposFinantialLibrary!.
        /// </summary>
        public static string dialog_message_error_plugin_softwarevendor_not_registered {
            get {
                return ResourceManager.GetString("dialog_message_error_plugin_softwarevendor_not_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главное меню.
        /// </summary>
        public static string global_application_main_menu {
            get {
                return ResourceManager.GetString("global_application_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string global_application_setup {
            get {
                return ResourceManager.GetString("global_application_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть приложение.
        /// </summary>
        public static string global_application_close {
            get {
                return ResourceManager.GetString("global_application_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        public static string global_article {
            get {
                return ResourceManager.GetString("global_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары.
        /// </summary>
        public static string global_articles {
            get {
                return ResourceManager.GetString("global_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код товара.
        /// </summary>
        public static string global_article_code {
            get {
                return ResourceManager.GetString("global_article_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Семейство товаров.
        /// </summary>
        public static string global_article_family {
            get {
                return ResourceManager.GetString("global_article_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсемейство товаров.
        /// </summary>
        public static string global_article_subfamily {
            get {
                return ResourceManager.GetString("global_article_subfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип товара.
        /// </summary>
        public static string global_article_type {
            get {
                return ResourceManager.GetString("global_article_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        public static string global_customer {
            get {
                return ResourceManager.GetString("global_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        public static string global_customers {
            get {
                return ResourceManager.GetString("global_customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя клиента.
        /// </summary>
        public static string global_customer_name {
            get {
                return ResourceManager.GetString("global_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес клиента.
        /// </summary>
        public static string global_customer_address {
            get {
                return ResourceManager.GetString("global_customer_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документ.
        /// </summary>
        public static string global_document {
            get {
                return ResourceManager.GetString("global_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы.
        /// </summary>
        public static string global_documents {
            get {
                return ResourceManager.GetString("global_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счет.
        /// </summary>
        public static string global_invoice {
            get {
                return ResourceManager.GetString("global_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счета.
        /// </summary>
        public static string global_invoices {
            get {
                return ResourceManager.GetString("global_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чек.
        /// </summary>
        public static string global_receipt {
            get {
                return ResourceManager.GetString("global_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чеки.
        /// </summary>
        public static string global_receipts {
            get {
                return ResourceManager.GetString("global_receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string global_price {
            get {
                return ResourceManager.GetString("global_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string global_total {
            get {
                return ResourceManager.GetString("global_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Промежуточный итог.
        /// </summary>
        public static string global_subtotal {
            get {
                return ResourceManager.GetString("global_subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налог.
        /// </summary>
        public static string global_tax {
            get {
                return ResourceManager.GetString("global_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скидка.
        /// </summary>
        public static string global_discount {
            get {
                return ResourceManager.GetString("global_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string global_quantity {
            get {
                return ResourceManager.GetString("global_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string global_user {
            get {
                return ResourceManager.GetString("global_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string global_users {
            get {
                return ResourceManager.GetString("global_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string global_password {
            get {
                return ResourceManager.GetString("global_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string global_login {
            get {
                return ResourceManager.GetString("global_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string global_logout {
            get {
                return ResourceManager.GetString("global_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать параметр конфигурации.
        /// </summary>
        public static string window_title_edit_configurationpreferenceparameter {
            get {
                return ResourceManager.GetString("window_title_edit_configurationpreferenceparameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активный.
        /// </summary>
        public static string global_status_active {
            get {
                return ResourceManager.GetString("global_status_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неактивный.
        /// </summary>
        public static string global_status_inactive {
            get {
                return ResourceManager.GetString("global_status_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включен.
        /// </summary>
        public static string global_status_enabled {
            get {
                return ResourceManager.GetString("global_status_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключен.
        /// </summary>
        public static string global_status_disabled {
            get {
                return ResourceManager.GetString("global_status_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string global_date {
            get {
                return ResourceManager.GetString("global_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string global_time {
            get {
                return ResourceManager.GetString("global_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время.
        /// </summary>
        public static string global_datetime {
            get {
                return ResourceManager.GetString("global_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string global_yes {
            get {
                return ResourceManager.GetString("global_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string global_no {
            get {
                return ResourceManager.GetString("global_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string global_confirm {
            get {
                return ResourceManager.GetString("global_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string global_warning {
            get {
                return ResourceManager.GetString("global_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string global_info {
            get {
                return ResourceManager.GetString("global_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно.
        /// </summary>
        public static string global_success {
            get {
                return ResourceManager.GetString("global_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка POS....
        /// </summary>
        public static string global_load {
            get {
                return ResourceManager.GetString("global_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание базы данных POS....
        /// </summary>
        public static string global_load_first_time {
            get {
                return ResourceManager.GetString("global_load_first_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заметки.
        /// </summary>
        public static string global_notes {
            get {
                return ResourceManager.GetString("global_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string global_record_code {
            get {
                return ResourceManager.GetString("global_record_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код дилера.
        /// </summary>
        public static string global_record_code_dealer {
            get {
                return ResourceManager.GetString("global_record_code_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали.
        /// </summary>
        public static string global_record_main_detail {
            get {
                return ResourceManager.GetString("global_record_main_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порядок.
        /// </summary>
        public static string global_record_order {
            get {
                return ResourceManager.GetString("global_record_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ.
        /// </summary>
        public static string global_token {
            get {
                return ResourceManager.GetString("global_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string global_treeview_false {
            get {
                return ResourceManager.GetString("global_treeview_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string global_treeview_true {
            get {
                return ResourceManager.GetString("global_treeview_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример допустимых значений: [{0}].
        /// </summary>
        public static string global_prefparam_value_tip_format {
            get {
                return ResourceManager.GetString("global_prefparam_value_tip_format", resourceCulture);
            }
        }
    }
}
