<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CleverPos.Modules</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v23.2">
      <HintPath>$(MSBuildThisFileDirectory)..\libs\xpo_23_2_6\DevExpress.Data.v23.2.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpo.v23.2">
      <HintPath>$(MSBuildThisFileDirectory)..\libs\xpo_23_2_6\DevExpress.Xpo.v23.2.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="log4net">
      <HintPath>$(MSBuildThisFileDirectory)..\libs\log4net_2_0_17\log4net.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicPOS.Data\LogicPOS.Data.csproj" />
    <ProjectReference Include="..\LogicPOS.Globalization\LogicPOS.Globalization.csproj" />
    <ProjectReference Include="..\LogicPOS.Plugin\LogicPOS.Plugin.csproj" />
    <ProjectReference Include="..\LogicPOS.Settings\LogicPOS.Settings.csproj" />
    <ProjectReference Include="..\LogicPOS.Utility\LogicPOS.Utility.csproj" />
  </ItemGroup>

</Project>
