inherited SalePinCodeForm: TSalePinCodeForm
  Caption = #1042#1074#1086#1076' '#1055#1048#1053'-'#1082#1086#1076#1072
  ClientHeight = 320
  ClientWidth = 584
  Color = clBtnFace
  ExplicitWidth = 590
  ExplicitHeight = 346
  PixelsPerInch = 96
  TextHeight = 14
  inherited Panel1: TPanel
    Width = 570
    Height = 278
    ExplicitWidth = 570
    ExplicitHeight = 278
    object Panel2: TPanel
      Left = 2
      Top = 2
      Width = 356
      Height = 274
      Align = alClient
      TabOrder = 0
      object lbName: TLabel
        Left = 1
        Top = 1
        Width = 354
        Height = 46
        Margins.Left = 2
        Margins.Top = 2
        Margins.Right = 2
        Margins.Bottom = 2
        Align = alTop
        Alignment = taCenter
        Caption = #1044#1083#1103' '#1091#1076#1072#1083#1077#1085#1080#1103' '#1090#1086#1074#1072#1088#1072'(-'#1086#1074') '#1074#1074#1077#1076#1080#1090#1077' '#1055#1048#1053'-'#1082#1086#1076'!'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clRed
        Font.Height = -19
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        WordWrap = True
        ExplicitWidth = 313
      end
      object edPinCode: TcxTextEdit
        Left = 61
        Top = 119
        Margins.Left = 2
        Margins.Top = 2
        Margins.Right = 2
        Margins.Bottom = 2
        ParentFont = False
        Properties.Alignment.Horz = taCenter
        Properties.EchoMode = eemPassword
        Properties.MaxLength = 6
        Properties.PasswordChar = '*'
        Properties.UseLeftAlignmentOnEditing = False
        Style.BorderStyle = ebsFlat
        Style.Font.Charset = RUSSIAN_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -24
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.StyleController = dxEditStyleController
        Style.IsFontAssigned = True
        TabOrder = 0
        Width = 217
      end
    end
    object pnlButton: TPanel
      Left = 358
      Top = 2
      Width = 210
      Height = 274
      Align = alRight
      TabOrder = 1
      object btn7: TcxButton
        Left = 11
        Top = 13
        Width = 60
        Height = 55
        Caption = '7'
        LookAndFeel.Kind = lfFlat
        TabOrder = 0
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn8: TcxButton
        Left = 76
        Top = 13
        Width = 60
        Height = 55
        Caption = '8'
        LookAndFeel.Kind = lfFlat
        TabOrder = 1
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn9: TcxButton
        Left = 141
        Top = 13
        Width = 60
        Height = 55
        Caption = '9'
        LookAndFeel.Kind = lfFlat
        TabOrder = 2
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn4: TcxButton
        Left = 11
        Top = 77
        Width = 60
        Height = 55
        Caption = '4'
        LookAndFeel.Kind = lfFlat
        TabOrder = 3
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn5: TcxButton
        Left = 76
        Top = 77
        Width = 60
        Height = 55
        Caption = '5'
        LookAndFeel.Kind = lfFlat
        TabOrder = 4
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn6: TcxButton
        Left = 141
        Top = 77
        Width = 60
        Height = 55
        Caption = '6'
        LookAndFeel.Kind = lfFlat
        TabOrder = 5
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn1: TcxButton
        Left = 11
        Top = 140
        Width = 60
        Height = 55
        Caption = '1'
        LookAndFeel.Kind = lfFlat
        TabOrder = 6
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn2: TcxButton
        Left = 76
        Top = 140
        Width = 60
        Height = 55
        Caption = '2'
        LookAndFeel.Kind = lfFlat
        TabOrder = 7
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn3: TcxButton
        Left = 141
        Top = 140
        Width = 60
        Height = 55
        Caption = '3'
        LookAndFeel.Kind = lfFlat
        TabOrder = 8
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btn0: TcxButton
        Left = 11
        Top = 203
        Width = 60
        Height = 55
        Caption = '0'
        LookAndFeel.Kind = lfFlat
        TabOrder = 9
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btn0Click
      end
      object btnBcksp: TcxButton
        Left = 76
        Top = 203
        Width = 60
        Height = 55
        Hint = #1059#1076#1072#1083#1080#1090#1100
        Caption = '<<'
        LookAndFeel.Kind = lfFlat
        ParentShowHint = False
        ShowHint = True
        TabOrder = 10
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = btnBckspClick
      end
    end
  end
  inherited btnOk: TcxButton
    Left = 415
    Top = 288
    ExplicitLeft = 415
    ExplicitTop = 288
  end
  inherited btnCancel: TcxButton
    Left = 502
    Top = 288
    ExplicitLeft = 502
    ExplicitTop = 288
  end
  inherited dxEditStyleController: TcxEditStyleController
    PixelsPerInch = 96
  end
end
