-- Update country names to Russian (run once on existing logicposdb.db)
-- Safe to re-run: sets Designation/Capital by stable Code2

UPDATE cfg_configurationcountry SET Designation = 'Андорра', Capital = 'Андорра-ла-Велья' WHERE Code2 = 'AD';
UPDATE cfg_configurationcountry SET Designation = 'Объединённые Арабские Эмираты', Capital = 'Абу-Даби' WHERE Code2 = 'AE';
UPDATE cfg_configurationcountry SET Designation = 'Афганистан', Capital = 'Кабул' WHERE Code2 = 'AF';
UPDATE cfg_configurationcountry SET Designation = 'Антигуа и Барбуда', Capital = 'Сент-Джонс' WHERE Code2 = 'AG';
UPDATE cfg_configurationcountry SET Designation = 'Ангилья', Capital = 'Валли' WHERE Code2 = 'AI';
UPDATE cfg_configurationcountry SET Designation = 'Албания', Capital = 'Тирана' WHERE Code2 = 'AL';
UPDATE cfg_configurationcountry SET Designation = 'Армения', Capital = 'Ереван' WHERE Code2 = 'AM';
UPDATE cfg_configurationcountry SET Designation = 'Нидерландские Антильские острова', Capital = 'Виллемстад' WHERE Code2 = 'AN';
UPDATE cfg_configurationcountry SET Designation = 'Ангола', Capital = 'Луанда' WHERE Code2 = 'AO';
UPDATE cfg_configurationcountry SET Designation = 'Антарктида', Capital = 'Максвелл-Бей' WHERE Code2 = 'AQ';
UPDATE cfg_configurationcountry SET Designation = 'Аргентина', Capital = 'Буэнос-Айрес' WHERE Code2 = 'AR';
UPDATE cfg_configurationcountry SET Designation = 'Американское Самоа', Capital = 'Паго-Паго' WHERE Code2 = 'AS';
UPDATE cfg_configurationcountry SET Designation = 'Австрия', Capital = 'Вена' WHERE Code2 = 'AT';
UPDATE cfg_configurationcountry SET Designation = 'Австралия', Capital = 'Канберра' WHERE Code2 = 'AU';
UPDATE cfg_configurationcountry SET Designation = 'Аруба', Capital = 'Ораньестад' WHERE Code2 = 'AW';
UPDATE cfg_configurationcountry SET Designation = 'Азербайджан', Capital = 'Баку' WHERE Code2 = 'AZ';
UPDATE cfg_configurationcountry SET Designation = 'Босния и Герцеговина', Capital = 'Сараево' WHERE Code2 = 'BA';
UPDATE cfg_configurationcountry SET Designation = 'Барбадос', Capital = 'Бриджтаун' WHERE Code2 = 'BB';
UPDATE cfg_configurationcountry SET Designation = 'Бангладеш', Capital = 'Дакка' WHERE Code2 = 'BD';
UPDATE cfg_configurationcountry SET Designation = 'Бельгия', Capital = 'Брюссель' WHERE Code2 = 'BE';
UPDATE cfg_configurationcountry SET Designation = 'Буркина-Фасо', Capital = 'Уагадугу' WHERE Code2 = 'BF';
UPDATE cfg_configurationcountry SET Designation = 'Болгария', Capital = 'София' WHERE Code2 = 'BG';
UPDATE cfg_configurationcountry SET Designation = 'Бахрейн', Capital = 'Манама' WHERE Code2 = 'BH';
UPDATE cfg_configurationcountry SET Designation = 'Бурунди', Capital = 'Бужумбура' WHERE Code2 = 'BI';
UPDATE cfg_configurationcountry SET Designation = 'Бенин', Capital = 'Порто-Ново' WHERE Code2 = 'BJ';
UPDATE cfg_configurationcountry SET Designation = 'Бермуды', Capital = 'Гамильтон' WHERE Code2 = 'BM';
UPDATE cfg_configurationcountry SET Designation = 'Бруней', Capital = 'Бандар-Сери-Бегаван' WHERE Code2 = 'BN';
UPDATE cfg_configurationcountry SET Designation = 'Боливия', Capital = 'Сукре' WHERE Code2 = 'BO';
UPDATE cfg_configurationcountry SET Designation = 'Бразилия', Capital = 'Бразилиа' WHERE Code2 = 'BR';
UPDATE cfg_configurationcountry SET Designation = 'Багамы', Capital = 'Нассау' WHERE Code2 = 'BS';
UPDATE cfg_configurationcountry SET Designation = 'Бутан', Capital = 'Тхимпху' WHERE Code2 = 'BT';
UPDATE cfg_configurationcountry SET Designation = 'Ботсвана', Capital = 'Габороне' WHERE Code2 = 'BW';
UPDATE cfg_configurationcountry SET Designation = 'Беларусь', Capital = 'Минск' WHERE Code2 = 'BY';
UPDATE cfg_configurationcountry SET Designation = 'Белиз', Capital = 'Бельмопан' WHERE Code2 = 'BZ';
UPDATE cfg_configurationcountry SET Designation = 'Канада', Capital = 'Оттава' WHERE Code2 = 'CA';
UPDATE cfg_configurationcountry SET Designation = 'Демократическая Республика Конго', Capital = 'Киншаса' WHERE Code2 = 'CD';
UPDATE cfg_configurationcountry SET Designation = 'Центральноафриканская Республика', Capital = 'Банги' WHERE Code2 = 'CF';
UPDATE cfg_configurationcountry SET Designation = 'Республика Конго', Capital = 'Браззавиль' WHERE Code2 = 'CG';
UPDATE cfg_configurationcountry SET Designation = 'Швейцария', Capital = 'Берн' WHERE Code2 = 'CH';
UPDATE cfg_configurationcountry SET Designation = 'Кот-д''Ивуар', Capital = 'Ямусукро' WHERE Code2 = 'CI';
UPDATE cfg_configurationcountry SET Designation = 'Острова Кука', Capital = 'Аваруа' WHERE Code2 = 'CK';
UPDATE cfg_configurationcountry SET Designation = 'Чили', Capital = 'Сантьяго' WHERE Code2 = 'CL';
UPDATE cfg_configurationcountry SET Designation = 'Камерун', Capital = 'Яунде' WHERE Code2 = 'CM';
UPDATE cfg_configurationcountry SET Designation = 'Китай', Capital = 'Пекин' WHERE Code2 = 'CN';
UPDATE cfg_configurationcountry SET Designation = 'Колумбия', Capital = 'Богота' WHERE Code2 = 'CO';
UPDATE cfg_configurationcountry SET Designation = 'Коста-Рика', Capital = 'Сан-Хосе' WHERE Code2 = 'CR';
UPDATE cfg_configurationcountry SET Designation = 'Куба', Capital = 'Гавана' WHERE Code2 = 'CU';
UPDATE cfg_configurationcountry SET Designation = 'Кабо-Верде', Capital = 'Прайя' WHERE Code2 = 'CV';
UPDATE cfg_configurationcountry SET Designation = 'Кипр', Capital = 'Никосия' WHERE Code2 = 'CY';
UPDATE cfg_configurationcountry SET Designation = 'Чехия', Capital = 'Прага' WHERE Code2 = 'CZ';
UPDATE cfg_configurationcountry SET Designation = 'Германия', Capital = 'Берлин' WHERE Code2 = 'DE';
UPDATE cfg_configurationcountry SET Designation = 'Джибути', Capital = 'Джибути' WHERE Code2 = 'DJ';
UPDATE cfg_configurationcountry SET Designation = 'Дания', Capital = 'Копенгаген' WHERE Code2 = 'DK';
UPDATE cfg_configurationcountry SET Designation = 'Доминика', Capital = 'Розо' WHERE Code2 = 'DM';
UPDATE cfg_configurationcountry SET Designation = 'Доминиканская Республика', Capital = 'Санто-Доминго' WHERE Code2 = 'DO';
UPDATE cfg_configurationcountry SET Designation = 'Алжир', Capital = 'Алжир' WHERE Code2 = 'DZ';
UPDATE cfg_configurationcountry SET Designation = 'Эквадор', Capital = 'Кито' WHERE Code2 = 'EC';
UPDATE cfg_configurationcountry SET Designation = 'Эстония', Capital = 'Таллин' WHERE Code2 = 'EE';
UPDATE cfg_configurationcountry SET Designation = 'Египет', Capital = 'Каир' WHERE Code2 = 'EG';
UPDATE cfg_configurationcountry SET Designation = 'Эритрея', Capital = 'Асмэра' WHERE Code2 = 'ER';
UPDATE cfg_configurationcountry SET Designation = 'Испания', Capital = 'Мадрид' WHERE Code2 = 'ES';
UPDATE cfg_configurationcountry SET Designation = 'Эфиопия', Capital = 'Аддис-Абеба' WHERE Code2 = 'ET';
UPDATE cfg_configurationcountry SET Designation = 'Финляндия', Capital = 'Хельсинки' WHERE Code2 = 'FI';
UPDATE cfg_configurationcountry SET Designation = 'Фиджи', Capital = 'Сува' WHERE Code2 = 'FJ';
UPDATE cfg_configurationcountry SET Designation = 'Фолклендские острова', Capital = 'Стэнли' WHERE Code2 = 'FK';
UPDATE cfg_configurationcountry SET Designation = 'Микронезия', Capital = 'Паликир' WHERE Code2 = 'FM';
UPDATE cfg_configurationcountry SET Designation = 'Фарерские острова', Capital = 'Торсхавн' WHERE Code2 = 'FO';
UPDATE cfg_configurationcountry SET Designation = 'Франция', Capital = 'Париж' WHERE Code2 = 'FR';
UPDATE cfg_configurationcountry SET Designation = 'Габон', Capital = 'Либревиль' WHERE Code2 = 'GA';
UPDATE cfg_configurationcountry SET Designation = 'Великобритания', Capital = 'Лондон' WHERE Code2 = 'GB';
UPDATE cfg_configurationcountry SET Designation = 'Гренада', Capital = 'Сент-Джорджес' WHERE Code2 = 'GD';
UPDATE cfg_configurationcountry SET Designation = 'Грузия', Capital = 'Тбилиси' WHERE Code2 = 'GE';
UPDATE cfg_configurationcountry SET Designation = 'Французская Гвиана', Capital = 'Кайенна' WHERE Code2 = 'GF';
UPDATE cfg_configurationcountry SET Designation = 'Гана', Capital = 'Аккра' WHERE Code2 = 'GH';
UPDATE cfg_configurationcountry SET Designation = 'Гибралтар', Capital = 'Гибралтар' WHERE Code2 = 'GI';
UPDATE cfg_configurationcountry SET Designation = 'Гренландия', Capital = 'Нуук' WHERE Code2 = 'GL';
UPDATE cfg_configurationcountry SET Designation = 'Гамбия', Capital = 'Банжул' WHERE Code2 = 'GM';
UPDATE cfg_configurationcountry SET Designation = 'Гвинея', Capital = 'Конакри' WHERE Code2 = 'GN';
UPDATE cfg_configurationcountry SET Designation = 'Гваделупа', Capital = 'Бас-Тер' WHERE Code2 = 'GP';
UPDATE cfg_configurationcountry SET Designation = 'Экваториальная Гвинея', Capital = 'Малабо' WHERE Code2 = 'GQ';
UPDATE cfg_configurationcountry SET Designation = 'Греция', Capital = 'Афины' WHERE Code2 = 'GR';
UPDATE cfg_configurationcountry SET Designation = 'Южная Георгия и Южные Сандвичевы острова', Capital = 'Гритвикен' WHERE Code2 = 'GS';
UPDATE cfg_configurationcountry SET Designation = 'Гватемала', Capital = 'Гватемала' WHERE Code2 = 'GT';
UPDATE cfg_configurationcountry SET Designation = 'Гуам', Capital = 'Хагатна' WHERE Code2 = 'GU';
UPDATE cfg_configurationcountry SET Designation = 'Гвинея-Бисау', Capital = 'Бисау' WHERE Code2 = 'GW';
UPDATE cfg_configurationcountry SET Designation = 'Гайана', Capital = 'Джорджтаун' WHERE Code2 = 'GY';
UPDATE cfg_configurationcountry SET Designation = 'Гонконг', Capital = 'Гонконг' WHERE Code2 = 'HK';
UPDATE cfg_configurationcountry SET Designation = 'Гондурас', Capital = 'Тегусигальпа' WHERE Code2 = 'HN';
UPDATE cfg_configurationcountry SET Designation = 'Хорватия', Capital = 'Загреб' WHERE Code2 = 'HR';
UPDATE cfg_configurationcountry SET Designation = 'Гаити', Capital = 'Порт-о-Пренс' WHERE Code2 = 'HT';
UPDATE cfg_configurationcountry SET Designation = 'Венгрия', Capital = 'Будапешт' WHERE Code2 = 'HU';
UPDATE cfg_configurationcountry SET Designation = 'Индонезия', Capital = 'Джакарта' WHERE Code2 = 'ID';
UPDATE cfg_configurationcountry SET Designation = 'Ирландия', Capital = 'Дублин' WHERE Code2 = 'IE';
UPDATE cfg_configurationcountry SET Designation = 'Израиль', Capital = 'Иерусалим' WHERE Code2 = 'IL';
UPDATE cfg_configurationcountry SET Designation = 'Индия', Capital = 'Нью-Дели' WHERE Code2 = 'IN';
UPDATE cfg_configurationcountry SET Designation = 'Британская территория в Индийском океане', Capital = 'Диего-Гарсия' WHERE Code2 = 'IO';
UPDATE cfg_configurationcountry SET Designation = 'Ирак', Capital = 'Багдад' WHERE Code2 = 'IQ';
UPDATE cfg_configurationcountry SET Designation = 'Иран', Capital = 'Тегеран' WHERE Code2 = 'IR';
UPDATE cfg_configurationcountry SET Designation = 'Исландия', Capital = 'Рейкьявик' WHERE Code2 = 'IS';
UPDATE cfg_configurationcountry SET Designation = 'Италия', Capital = 'Рим' WHERE Code2 = 'IT';
UPDATE cfg_configurationcountry SET Designation = 'Ямайка', Capital = 'Кингстон' WHERE Code2 = 'JM';
UPDATE cfg_configurationcountry SET Designation = 'Иордания', Capital = 'Амман' WHERE Code2 = 'JO';
UPDATE cfg_configurationcountry SET Designation = 'Япония', Capital = 'Токио' WHERE Code2 = 'JP';
UPDATE cfg_configurationcountry SET Designation = 'Кения', Capital = 'Найроби' WHERE Code2 = 'KE';
UPDATE cfg_configurationcountry SET Designation = 'Киргизия', Capital = 'Бишкек' WHERE Code2 = 'KG';
UPDATE cfg_configurationcountry SET Designation = 'Камбоджа', Capital = 'Пномпень' WHERE Code2 = 'KH';
UPDATE cfg_configurationcountry SET Designation = 'Кирибати', Capital = 'Тарава' WHERE Code2 = 'KI';
UPDATE cfg_configurationcountry SET Designation = 'Коморы', Capital = 'Морони' WHERE Code2 = 'KM';
UPDATE cfg_configurationcountry SET Designation = 'Сент-Китс и Невис', Capital = 'Бастер' WHERE Code2 = 'KN';
UPDATE cfg_configurationcountry SET Designation = 'Республика Корея', Capital = 'Сеул' WHERE Code2 = 'KR';
UPDATE cfg_configurationcountry SET Designation = 'Кувейт', Capital = 'Эль-Кувейт' WHERE Code2 = 'KW';
UPDATE cfg_configurationcountry SET Designation = 'Острова Кайман', Capital = 'Джорджтаун' WHERE Code2 = 'KY';
UPDATE cfg_configurationcountry SET Designation = 'Казахстан', Capital = 'Астана' WHERE Code2 = 'KZ';
UPDATE cfg_configurationcountry SET Designation = 'Лаос', Capital = 'Вьентьян' WHERE Code2 = 'LA';
UPDATE cfg_configurationcountry SET Designation = 'Ливан', Capital = 'Бейрут' WHERE Code2 = 'LB';
UPDATE cfg_configurationcountry SET Designation = 'Сент-Люсия', Capital = 'Кастри' WHERE Code2 = 'LC';
UPDATE cfg_configurationcountry SET Designation = 'Лихтенштейн', Capital = 'Вадуц' WHERE Code2 = 'LI';
UPDATE cfg_configurationcountry SET Designation = 'Шри-Ланка', Capital = 'Коломбо' WHERE Code2 = 'LK';
UPDATE cfg_configurationcountry SET Designation = 'Либерия', Capital = 'Монровия' WHERE Code2 = 'LR';
UPDATE cfg_configurationcountry SET Designation = 'Лесото', Capital = 'Масеру' WHERE Code2 = 'LS';
UPDATE cfg_configurationcountry SET Designation = 'Литва', Capital = 'Вильнюс' WHERE Code2 = 'LT';
UPDATE cfg_configurationcountry SET Designation = 'Люксембург', Capital = 'Люксембург' WHERE Code2 = 'LU';
UPDATE cfg_configurationcountry SET Designation = 'Латвия', Capital = 'Рига' WHERE Code2 = 'LV';
UPDATE cfg_configurationcountry SET Designation = 'Ливия', Capital = 'Триполи' WHERE Code2 = 'LY';
UPDATE cfg_configurationcountry SET Designation = 'Марокко', Capital = 'Рабат' WHERE Code2 = 'MA';
UPDATE cfg_configurationcountry SET Designation = 'Монако', Capital = 'Монако' WHERE Code2 = 'MC';
UPDATE cfg_configurationcountry SET Designation = 'Молдова', Capital = 'Кишинёв' WHERE Code2 = 'MD';
UPDATE cfg_configurationcountry SET Designation = 'Мадагаскар', Capital = 'Антананариву' WHERE Code2 = 'MG';
UPDATE cfg_configurationcountry SET Designation = 'Северная Македония', Capital = 'Скопье' WHERE Code2 = 'MK';
UPDATE cfg_configurationcountry SET Designation = 'Мали', Capital = 'Бамако' WHERE Code2 = 'ML';
UPDATE cfg_configurationcountry SET Designation = 'Мьянма', Capital = 'Нейпьидо' WHERE Code2 = 'MM';
UPDATE cfg_configurationcountry SET Designation = 'Монголия', Capital = 'Улан-Батор' WHERE Code2 = 'MN';
UPDATE cfg_configurationcountry SET Designation = 'Макао', Capital = 'Макао' WHERE Code2 = 'MO';
UPDATE cfg_configurationcountry SET Designation = 'Северные Марианские острова', Capital = 'Сайпан' WHERE Code2 = 'MP';
UPDATE cfg_configurationcountry SET Designation = 'Мартиника', Capital = 'Фор-де-Франс' WHERE Code2 = 'MQ';
UPDATE cfg_configurationcountry SET Designation = 'Мавритания', Capital = 'Нуакшот' WHERE Code2 = 'MR';
UPDATE cfg_configurationcountry SET Designation = 'Монтсеррат', Capital = 'Плимут' WHERE Code2 = 'MS';
UPDATE cfg_configurationcountry SET Designation = 'Мальта', Capital = 'Валлетта' WHERE Code2 = 'MT';
UPDATE cfg_configurationcountry SET Designation = 'Маврикий', Capital = 'Порт-Луи' WHERE Code2 = 'MU';
UPDATE cfg_configurationcountry SET Designation = 'Мальдивы', Capital = 'Мале' WHERE Code2 = 'MV';
UPDATE cfg_configurationcountry SET Designation = 'Малави', Capital = 'Лилонгве' WHERE Code2 = 'MW';
UPDATE cfg_configurationcountry SET Designation = 'Мексика', Capital = 'Мехико' WHERE Code2 = 'MX';
UPDATE cfg_configurationcountry SET Designation = 'Малайзия', Capital = 'Куала-Лумпур' WHERE Code2 = 'MY';
UPDATE cfg_configurationcountry SET Designation = 'Мозамбик', Capital = 'Мапуту' WHERE Code2 = 'MZ';
UPDATE cfg_configurationcountry SET Designation = 'Намибия', Capital = 'Виндхук' WHERE Code2 = 'NA';
UPDATE cfg_configurationcountry SET Designation = 'Новая Каледония', Capital = 'Нумеа' WHERE Code2 = 'NC';
UPDATE cfg_configurationcountry SET Designation = 'Нигер', Capital = 'Ниамей' WHERE Code2 = 'NE';
UPDATE cfg_configurationcountry SET Designation = 'Остров Норфолк', Capital = 'Кингстон' WHERE Code2 = 'NF';
UPDATE cfg_configurationcountry SET Designation = 'Нигерия', Capital = 'Абуджа' WHERE Code2 = 'NG';
UPDATE cfg_configurationcountry SET Designation = 'Никарагуа', Capital = 'Манагуа' WHERE Code2 = 'NI';
UPDATE cfg_configurationcountry SET Designation = 'Нидерланды', Capital = 'Амстердам' WHERE Code2 = 'NL';
UPDATE cfg_configurationcountry SET Designation = 'Норвегия', Capital = 'Осло' WHERE Code2 = 'NO';
UPDATE cfg_configurationcountry SET Designation = 'Непал', Capital = 'Катманду' WHERE Code2 = 'NP';
UPDATE cfg_configurationcountry SET Designation = 'Науру', Capital = 'Ярен' WHERE Code2 = 'NR';
UPDATE cfg_configurationcountry SET Designation = 'Ниуэ', Capital = 'Алофи' WHERE Code2 = 'NU';
UPDATE cfg_configurationcountry SET Designation = 'Новая Зеландия', Capital = 'Веллингтон' WHERE Code2 = 'NZ';
UPDATE cfg_configurationcountry SET Designation = 'Оман', Capital = 'Маскат' WHERE Code2 = 'OM';
UPDATE cfg_configurationcountry SET Designation = 'Панама', Capital = 'Панама' WHERE Code2 = 'PA';
UPDATE cfg_configurationcountry SET Designation = 'Перу', Capital = 'Лима' WHERE Code2 = 'PE';
UPDATE cfg_configurationcountry SET Designation = 'Французская Полинезия', Capital = 'Папеэте' WHERE Code2 = 'PF';
UPDATE cfg_configurationcountry SET Designation = 'Папуа — Новая Гвинея', Capital = 'Порт-Морсби' WHERE Code2 = 'PG';
UPDATE cfg_configurationcountry SET Designation = 'Филиппины', Capital = 'Манила' WHERE Code2 = 'PH';
UPDATE cfg_configurationcountry SET Designation = 'Пакистан', Capital = 'Исламабад' WHERE Code2 = 'PK';
UPDATE cfg_configurationcountry SET Designation = 'Польша', Capital = 'Варшава' WHERE Code2 = 'PL';
UPDATE cfg_configurationcountry SET Designation = 'Пуэрто-Рико', Capital = 'Сан-Хуан' WHERE Code2 = 'PR';
UPDATE cfg_configurationcountry SET Designation = 'Португалия', Capital = 'Лиссабон' WHERE Code2 = 'PT';
UPDATE cfg_configurationcountry SET Designation = 'Палау', Capital = 'Мелекеок' WHERE Code2 = 'PW';
UPDATE cfg_configurationcountry SET Designation = 'Парагвай', Capital = 'Асунсьон' WHERE Code2 = 'PY';
UPDATE cfg_configurationcountry SET Designation = 'Катар', Capital = 'Доха' WHERE Code2 = 'QA';
UPDATE cfg_configurationcountry SET Designation = 'Реюньон', Capital = 'Сен-Дени' WHERE Code2 = 'RE';
UPDATE cfg_configurationcountry SET Designation = 'Румыния', Capital = 'Бухарест' WHERE Code2 = 'RO';
UPDATE cfg_configurationcountry SET Designation = 'Россия', Capital = 'Москва' WHERE Code2 = 'RU';
UPDATE cfg_configurationcountry SET Designation = 'Руанда', Capital = 'Кигали' WHERE Code2 = 'RW';
UPDATE cfg_configurationcountry SET Designation = 'Саудовская Аравия', Capital = 'Эр-Рияд' WHERE Code2 = 'SA';
UPDATE cfg_configurationcountry SET Designation = 'Соломоновы Острова', Capital = 'Хониара' WHERE Code2 = 'SB';
UPDATE cfg_configurationcountry SET Designation = 'Сейшельские Острова', Capital = 'Виктория' WHERE Code2 = 'SC';
UPDATE cfg_configurationcountry SET Designation = 'Судан', Capital = 'Хартум' WHERE Code2 = 'SD';
UPDATE cfg_configurationcountry SET Designation = 'Швеция', Capital = 'Стокгольм' WHERE Code2 = 'SE';
UPDATE cfg_configurationcountry SET Designation = 'Сингапур', Capital = 'Сингапур' WHERE Code2 = 'SG';
UPDATE cfg_configurationcountry SET Designation = 'Словения', Capital = 'Любляна' WHERE Code2 = 'SI';
UPDATE cfg_configurationcountry SET Designation = 'Словакия', Capital = 'Братислава' WHERE Code2 = 'SK';
UPDATE cfg_configurationcountry SET Designation = 'Сьерра-Леоне', Capital = 'Фритаун' WHERE Code2 = 'SL';
UPDATE cfg_configurationcountry SET Designation = 'Сан-Марино', Capital = 'Сан-Марино' WHERE Code2 = 'SM';
UPDATE cfg_configurationcountry SET Designation = 'Сенегал', Capital = 'Дакар' WHERE Code2 = 'SN';
UPDATE cfg_configurationcountry SET Designation = 'Сомали', Capital = 'Могадишо' WHERE Code2 = 'SO';
UPDATE cfg_configurationcountry SET Designation = 'Суринам', Capital = 'Парамарибо' WHERE Code2 = 'SR';
UPDATE cfg_configurationcountry SET Designation = 'Сан-Томе и Принсипи', Capital = 'Сан-Томе' WHERE Code2 = 'ST';
UPDATE cfg_configurationcountry SET Designation = 'Сальвадор', Capital = 'Сан-Сальвадор' WHERE Code2 = 'SV';
UPDATE cfg_configurationcountry SET Designation = 'Сирия', Capital = 'Дамаск' WHERE Code2 = 'SY';
UPDATE cfg_configurationcountry SET Designation = 'Эсватини', Capital = 'Мбабане' WHERE Code2 = 'SZ';
UPDATE cfg_configurationcountry SET Designation = 'Чад', Capital = 'Нджамена' WHERE Code2 = 'TD';
UPDATE cfg_configurationcountry SET Designation = 'Того', Capital = 'Ломе' WHERE Code2 = 'TG';
UPDATE cfg_configurationcountry SET Designation = 'Таиланд', Capital = 'Бангкок' WHERE Code2 = 'TH';
UPDATE cfg_configurationcountry SET Designation = 'Таджикистан', Capital = 'Душанбе' WHERE Code2 = 'TJ';
UPDATE cfg_configurationcountry SET Designation = 'Токелау', Capital = 'Атафу' WHERE Code2 = 'TK';
UPDATE cfg_configurationcountry SET Designation = 'Восточный Тимор', Capital = 'Дили' WHERE Code2 = 'TL';
UPDATE cfg_configurationcountry SET Designation = 'Туркменистан', Capital = 'Ашхабад' WHERE Code2 = 'TM';
UPDATE cfg_configurationcountry SET Designation = 'Тунис', Capital = 'Тунис' WHERE Code2 = 'TN';
UPDATE cfg_configurationcountry SET Designation = 'Тонга', Capital = 'Нукуалофа' WHERE Code2 = 'TO';
UPDATE cfg_configurationcountry SET Designation = 'Турция', Capital = 'Анкара' WHERE Code2 = 'TR';
UPDATE cfg_configurationcountry SET Designation = 'Тринидад и Тобаго', Capital = 'Порт-оф-Спейн' WHERE Code2 = 'TT';
UPDATE cfg_configurationcountry SET Designation = 'Тувалу', Capital = 'Фунафути' WHERE Code2 = 'TV';
UPDATE cfg_configurationcountry SET Designation = 'Тайвань', Capital = 'Тайбэй' WHERE Code2 = 'TW';
UPDATE cfg_configurationcountry SET Designation = 'Танзания', Capital = 'Додома' WHERE Code2 = 'TZ';
UPDATE cfg_configurationcountry SET Designation = 'Украина', Capital = 'Киев' WHERE Code2 = 'UA';
UPDATE cfg_configurationcountry SET Designation = 'Уганда', Capital = 'Кампала' WHERE Code2 = 'UG';
UPDATE cfg_configurationcountry SET Designation = 'Внешние малые острова США', Capital = 'Вашингтон' WHERE Code2 = 'UM';
UPDATE cfg_configurationcountry SET Designation = 'Соединённые Штаты Америки', Capital = 'Вашингтон' WHERE Code2 = 'US';
UPDATE cfg_configurationcountry SET Designation = 'Уругвай', Capital = 'Монтевидео' WHERE Code2 = 'UY';
UPDATE cfg_configurationcountry SET Designation = 'Узбекистан', Capital = 'Ташкент' WHERE Code2 = 'UZ';
UPDATE cfg_configurationcountry SET Designation = 'Ватикан', Capital = 'Ватикан' WHERE Code2 = 'VA';
UPDATE cfg_configurationcountry SET Designation = 'Сент-Винсент и Гренадины', Capital = 'Кингстаун' WHERE Code2 = 'VC';
UPDATE cfg_configurationcountry SET Designation = 'Венесуэла', Capital = 'Каракас' WHERE Code2 = 'VE';
UPDATE cfg_configurationcountry SET Designation = 'Виргинские острова (Великобритания)', Capital = 'Роуд-Таун' WHERE Code2 = 'VG';
UPDATE cfg_configurationcountry SET Designation = 'Виргинские острова (США)', Capital = 'Шарлотта-Амалия' WHERE Code2 = 'VI';
UPDATE cfg_configurationcountry SET Designation = 'Вьетнам', Capital = 'Ханой' WHERE Code2 = 'VN';
UPDATE cfg_configurationcountry SET Designation = 'Вануату', Capital = 'Порт-Вила' WHERE Code2 = 'VU';
UPDATE cfg_configurationcountry SET Designation = 'Самоа', Capital = 'Апиа' WHERE Code2 = 'WS';
UPDATE cfg_configurationcountry SET Designation = 'Йемен', Capital = 'Сана' WHERE Code2 = 'YE';
UPDATE cfg_configurationcountry SET Designation = 'Майотта', Capital = 'Мамудзу' WHERE Code2 = 'YT';
UPDATE cfg_configurationcountry SET Designation = 'Южно-Африканская Республика', Capital = 'Претория' WHERE Code2 = 'ZA';
UPDATE cfg_configurationcountry SET Designation = 'Замбия', Capital = 'Лусака' WHERE Code2 = 'ZM';
UPDATE cfg_configurationcountry SET Designation = 'Зимбабве', Capital = 'Хараре' WHERE Code2 = 'ZW';
UPDATE cfg_configurationcountry SET Designation = 'Португалия — автономный регион Азорские острова', Capital = 'Понта-Делгада' WHERE Code2 = 'PT-AC';
UPDATE cfg_configurationcountry SET Designation = 'Португалия — автономный регион Мадейра', Capital = 'Фуншал' WHERE Code2 = 'PT-MA';

UPDATE cfg_configurationcountry SET Designation = '-- Выберите --' WHERE Oid = '00000000-0000-0000-0000-000000000001';
