<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CleverPos.Persistence</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v23.2">
      <HintPath>$(MSBuildThisFileDirectory)..\libs\xpo_23_2_6\DevExpress.Data.v23.2.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpo.v23.2">
      <HintPath>$(MSBuildThisFileDirectory)..\libs\xpo_23_2_6\DevExpress.Xpo.v23.2.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicPOS.Settings\LogicPOS.Settings.csproj" />
  </ItemGroup>

</Project>
