<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>CleverPos.Persistence</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v23.2">
      <HintPath>..\libs\xpo_23_2_6\DevExpress.Data.v23.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Xpo.v23.2">
      <HintPath>..\libs\xpo_23_2_6\DevExpress.Xpo.v23.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicPOS.Settings\LogicPOS.Settings.csproj" />
  </ItemGroup>

</Project>
