// <auto-generated />
using System;
using CleverPos.License.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleverPos.License.Api.Migrations
{
    [DbContext(typeof(LicenseDbContext))]
    [Migration("20260811165847_AddOwnerAccountsAndBin")]
    partial class AddOwnerAccountsAndBin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CleverPos.License.Api.Models.LicenseAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Allowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ComputerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("LicenseId");

                    b.HasIndex("LicenseKey");

                    b.ToTable("license_access_logs", (string)null);
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicenseActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ComputerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId", "ComputerId")
                        .IsUnique();

                    b.ToTable("license_activations", (string)null);
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicensePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("int");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId", "PeriodYear", "PeriodMonth")
                        .IsUnique();

                    b.ToTable("license_payments", (string)null);
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicenseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bin")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("MaxActivations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.OwnerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("owner_accounts", (string)null);
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.OwnerLicenseLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("OwnerId", "LicenseId")
                        .IsUnique();

                    b.ToTable("owner_license_links", (string)null);
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicenseAccessLog", b =>
                {
                    b.HasOne("CleverPos.License.Api.Models.LicenseRecord", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("License");
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicenseActivation", b =>
                {
                    b.HasOne("CleverPos.License.Api.Models.LicenseRecord", "License")
                        .WithMany("Activations")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicensePayment", b =>
                {
                    b.HasOne("CleverPos.License.Api.Models.LicenseRecord", "License")
                        .WithMany("Payments")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.OwnerLicenseLink", b =>
                {
                    b.HasOne("CleverPos.License.Api.Models.LicenseRecord", "License")
                        .WithMany("OwnerLinks")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleverPos.License.Api.Models.OwnerAccount", "Owner")
                        .WithMany("LicenseLinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.LicenseRecord", b =>
                {
                    b.Navigation("Activations");

                    b.Navigation("OwnerLinks");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CleverPos.License.Api.Models.OwnerAccount", b =>
                {
                    b.Navigation("LicenseLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
